import type {Metadata} from 'next';
import './globals.css';
import ConfigProvider from 'antd/es/config-provider';
import {Plus_Jakarta_Sans} from 'next/font/google';
import theme from './style/theme';
import Providers from './Provider';
import {getServerSession} from 'next-auth/next';
import {authOptions} from './api/auth/[...nextauth]/route';
import ClientSessionProvider from './provider/ClientSessionProvider';

const inter = Plus_Jakarta_Sans({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'ResellerOS',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <ConfigProvider theme={theme}>
      <html lang="en">
        <body className={inter.className}>
          <ClientSessionProvider session={session}>
            <Providers>{children}</Providers>
          </ClientSessionProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
