import {ThemeConfig} from 'antd/es/config-provider/context';

const theme: ThemeConfig = {
  token: {
    fontFamily: '__Plus_Jakarta_Sans_d21556',
    colorPrimary: '#1c3557',
    colorPrimaryText: '#0D0D0D',
    colorPrimaryBg: '#E8EBEE',
    colorPrimaryBorder: '#1c3557',
    colorPrimaryHover: '#14263E',
    colorPrimaryActive: '#31576f',
    colorError: '#EB445A',
    colorErrorBg: '#FDECEF',
    colorErrorBorder: '#631d26',
    colorErrorHover: '#eb445a',
    colorErrorActive: '#d63e52',
    colorSuccess: '#1EB159',
    colorSuccessBg: '#E9F7EE',
    colorSuccessBorder: '#116131',
    colorSuccessHover: '#116131',
    colorSuccessActive: '#116131',
    colorWarning: '#ECB816',
    colorWarningBg: '#FDF8E8',
    colorWarningBorder: '#634d09',
    colorWarningHover: '#82650c',
    colorWarningActive: '#634d09',
    colorLink: '#3DA5D9',
    colorInfoActive: '#64B7E1',
    colorTextSecondary: '#AEB6C3',
    colorInfo: '#2364AA',
    colorInfoBg: '#EDEFF2',
    colorInfoBorder: '#949494',
    colorInfoHover: '#ECF2F5',
    colorLinkHover: '#457B9D',
    colorLinkActive: '#ECF6FB',
    // colorText: "#2A2A2A",
    // colorTextSecondary: "#767676",
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#ffffff',
    colorBorder: '#C7CDD5',
    colorBorderSecondary: '#BBCFE5',
    // colorSplit: '#EF697B',
    colorIcon: '#EF697B',
    colorInfoBgHover: '#E9F0F7',
    colorTextDisabled: '#6C97C6',
  },
  components: {
    Button: {
      borderRadius: 12,
      colorText: '#1c3557',
      colorBorder: '#1c3557',
      boxShadow: 'none',
    },
  },
};
export default theme;
