export const selectDataForProduct = [
  {value: 'Professional Services', label: 'Professional Services'},
  {value: 'Subscriptions', label: 'Subscriptions'},
  {value: 'Products', label: 'Products'},
  {value: 'Maintenance', label: 'Maintenance'},
];

export const selectData = [
  {value: 'Product Family', label: 'Product Family'},
  {value: 'Pricing Method', label: 'Pricing Method'},
  {value: 'Vendor/Disti', label: 'Vendor/Disti'},
  {value: 'OEM', label: 'OEM'},
];

export const pricingMethod = [
  {value: 'cost_percentage', label: 'Cost + %'},
  {value: 'cost_dollar', label: 'Cost + $'},
  {value: 'list_percentage', label: 'List - %'},
  {value: 'list_dollar', label: 'List - $'},
  {value: 'manual', label: 'Manual'},
  {value: 'gp', label: 'GP'},
];

export const dummyData = [
  {
    id: 7,
    is_deleted: false,
    quote_id: 2,
    product_id: 1,
    bundle_id: null,
    line_number: '1',
    adjusted_price: '$21,114.59',
    product_code: '422-BRSI',
    line_amount: '$42,229.18',
    list_price: '$31,302.32',
    description:
      'PowerTower PT549 Server\nDell Federal Systems L.P. c/o Dell USA L.P.\n422-BRSR',
    quantity: '2',
    createdAt: '2023-12-14T17:32:49.051Z',
    updatedAt: '2023-12-14T17:32:49.051Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 1,
      is_deleted: null,
      product_code: '422-BRSI',
      description:
        'PowerTower PT549 Server\nDell Federal Systems L.P. c/o Dell USA L.P.\n422-BRSR',
      part_no: null,
      line_amount: '$42,229.18',
      list_price: '$31,302.32',
      line_number: '1',
      quantity: '2',
      adjusted_price: '$21,114.59',
      product_family: null,
      createdAt: '2023-12-14T12:33:05.164Z',
      updatedAt: '2023-12-14T12:33:05.164Z',
    },
    Bundle: null,
  },
  {
    id: 8,
    is_deleted: false,
    quote_id: 2,
    product_id: 2,
    bundle_id: null,
    line_number: '2',
    adjusted_price: '$0.00',
    product_code: '796-5228',
    line_amount: '$0.00',
    list_price: '$0.00',
    description:
      'Dell Hardware Limited Warranty Plus On-Site\nService\nDell Federal Systems L.P. c/o Dell USA L.P. -\n796-5225',
    quantity: '2',
    createdAt: '2023-12-14T17:32:49.051Z',
    updatedAt: '2023-12-14T17:32:49.051Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 2,
      is_deleted: null,
      product_code: '796-5228',
      description:
        'Dell Hardware Limited Warranty Plus On-Site\nService\nDell Federal Systems L.P. c/o Dell USA L.P. -\n796-5225',
      part_no: null,
      line_amount: '$0.00',
      list_price: '$0.00',
      line_number: '2',
      quantity: '2',
      adjusted_price: '$0.00',
      product_family: null,
      createdAt: '2023-12-14T12:33:05.665Z',
      updatedAt: '2023-12-14T12:33:05.665Z',
    },
    Bundle: null,
  },
  {
    id: 9,
    is_deleted: false,
    quote_id: 2,
    product_id: 3,
    bundle_id: null,
    line_number: '3',
    adjusted_price: '$0.00',
    product_code: '796-6299',
    line_amount: '$0.00',
    list_price: '$0.00',
    description:
      'ProSupport: Next Business Day On-Site Service\nAfter Problem Diagnosis, 3 Years\nDell Federal Systems L.P. c/o Dell USA L.P.\n796-6291',
    quantity: '2',
    createdAt: '2023-12-14T17:32:49.051Z',
    updatedAt: '2023-12-14T17:32:49.051Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 3,
      is_deleted: null,
      product_code: '796-6299',
      description:
        'ProSupport: Next Business Day On-Site Service\nAfter Problem Diagnosis, 3 Years\nDell Federal Systems L.P. c/o Dell USA L.P.\n796-6291',
      part_no: null,
      line_amount: '$0.00',
      list_price: '$0.00',
      line_number: '3',
      quantity: '2',
      adjusted_price: '$0.00',
      product_family: null,
      createdAt: '2023-12-14T12:33:06.159Z',
      updatedAt: '2023-12-14T12:33:06.159Z',
    },
    Bundle: null,
  },
  {
    id: 13,
    is_deleted: false,
    quote_id: 2,
    product_id: 1,
    bundle_id: null,
    line_number: '1',
    adjusted_price: '$21,114.59',
    product_code: '422-BRSI',
    line_amount: '$42,229.18',
    list_price: '$31,302.32',
    description:
      'PowerTower PT549 Server\nDell Federal Systems L.P. c/o Dell USA L.P.\n422-BRSR',
    quantity: '2',
    createdAt: '2023-12-14T17:40:08.092Z',
    updatedAt: '2023-12-14T17:40:08.092Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 1,
      is_deleted: null,
      product_code: '422-BRSI',
      description:
        'PowerTower PT549 Server\nDell Federal Systems L.P. c/o Dell USA L.P.\n422-BRSR',
      part_no: null,
      line_amount: '$42,229.18',
      list_price: '$31,302.32',
      line_number: '1',
      quantity: '2',
      adjusted_price: '$21,114.59',
      product_family: null,
      createdAt: '2023-12-14T12:33:05.164Z',
      updatedAt: '2023-12-14T12:33:05.164Z',
    },
    Bundle: null,
  },
  {
    id: 14,
    is_deleted: false,
    quote_id: 2,
    product_id: 2,
    bundle_id: null,
    line_number: '2',
    adjusted_price: '$0.00',
    product_code: '796-5228',
    line_amount: '$0.00',
    list_price: '$0.00',
    description:
      'Dell Hardware Limited Warranty Plus On-Site\nService\nDell Federal Systems L.P. c/o Dell USA L.P. -\n796-5225',
    quantity: '2',
    createdAt: '2023-12-14T17:40:08.092Z',
    updatedAt: '2023-12-14T17:40:08.092Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 2,
      is_deleted: null,
      product_code: '796-5228',
      description:
        'Dell Hardware Limited Warranty Plus On-Site\nService\nDell Federal Systems L.P. c/o Dell USA L.P. -\n796-5225',
      part_no: null,
      line_amount: '$0.00',
      list_price: '$0.00',
      line_number: '2',
      quantity: '2',
      adjusted_price: '$0.00',
      product_family: null,
      createdAt: '2023-12-14T12:33:05.665Z',
      updatedAt: '2023-12-14T12:33:05.665Z',
    },
    Bundle: null,
  },
  {
    id: 15,
    is_deleted: false,
    quote_id: 2,
    product_id: 3,
    bundle_id: null,
    line_number: '3',
    adjusted_price: '$0.00',
    product_code: '796-6299',
    line_amount: '$0.00',
    list_price: '$0.00',
    description:
      'ProSupport: Next Business Day On-Site Service\nAfter Problem Diagnosis, 3 Years\nDell Federal Systems L.P. c/o Dell USA L.P.\n796-6291',
    quantity: '2',
    createdAt: '2023-12-14T17:40:08.092Z',
    updatedAt: '2023-12-14T17:40:08.092Z',
    Quote: {
      id: 2,
      user_id: null,
      is_deleted: false,
      cage_code: '2Q4B6',
      credit_cards: null,
      customer_address: null,
      customer_city: 'Mechanicsville,',
      customer_contact: null,
      customer_email: null,
      customer_name: 'Stark',
      customer_phone: '(804) 723-1007',
      customer_state: 'CA',
      customer_street: 'Defender HWY',
      customer_zip: '49260',
      deal_id: null,
      distributor_address: null,
      distributor_city: null,
      distributor_contact: 'Andrew Roller',
      distributor_email: 'Andrew.Roller@Roller.com',
      distributor_fax: null,
      distributor_name: 'Technology Corp.',
      distributor_phone: '(804)',
      distributor_state: 'VA',
      distributor_street: 'Suite 422',
      distributor_zip: '23111',
      duns_number: null,
      expiration_date: null,
      fob_shipping: 'FOB',
      ftin: '61-3278702',
      oem_name: null,
      payment_terms: null,
      quote_amount: '$42,229.18',
      quote_date: '7/7/2045',
      quote_number: '43593594',
      remit_to: null,
      reseller_address: null,
      reseller_city: null,
      reseller_contact: 'Roller',
      reseller_email: null,
      reseller_name: 'Roller',
      reseller_phone: null,
      reseller_state: null,
      reseller_street: null,
      reseller_zip: null,
      shipping: null,
      shipping_amount: '$0.00',
      subtotal: '$42,229.18',
      uei: null,
      is_completed: false,
      is_drafted: true,
      file_name: null,
      opportunity: null,
      createdAt: '2023-12-14T17:32:44.281Z',
      updatedAt: '2023-12-14T18:17:56.244Z',
    },
    Product: {
      id: 3,
      is_deleted: null,
      product_code: '796-6299',
      description:
        'ProSupport: Next Business Day On-Site Service\nAfter Problem Diagnosis, 3 Years\nDell Federal Systems L.P. c/o Dell USA L.P.\n796-6291',
      part_no: null,
      line_amount: '$0.00',
      list_price: '$0.00',
      line_number: '3',
      quantity: '2',
      adjusted_price: '$0.00',
      product_family: null,
      createdAt: '2023-12-14T12:33:06.159Z',
      updatedAt: '2023-12-14T12:33:06.159Z',
    },
    Bundle: null,
  },
];
