name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_ISLAND_048EFF41E }}
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          app_build_command: 'npm run build'
          api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
          github_id_token: ${{ steps.idtoken.outputs.result }}
        env:
          NEXT_PUBLIC_SECRET_KEY: '5234523@RyVDUEUDfdsidjfb9865BDBHIhfidfbidgbirbgvifvWENB42354$@4MLMP546cdscujdbc'
          SECRET_KEY: '2b06d5d8a095a26337ad152eae7229d030aa9acbcc3763b0fb365c28bff5577d'
          SALESFORCE_CONSUMER_KEY: '3MVG9HB6vm3GZZR.h84pmASRrbtPTbINgzTbiQPOqcvKVYPEiEbbyZ_0sBAGY97V44ZhUvFEGKwNCFefR4mId'
          SALESFORCE_SECRET: '904B8F5C7A17217AAC08AF05AA5D4E23E2ABDEFAF82C123B89DD6550455DEA9D'
          NEXT_PUBLIC_SERVER_API_URL: 'https://dev-api.reselleros.com'
          CONSUMER_KEY: '3MVG9HB6vm3GZZR.h84pmASRrblHW95mS8Bpu6bzoqEXHsrYavKNJRMg0px3dl8.aHED6Y9i9ZE5D_EQx20Jk'
          CONSUMER_SECERT: '6FDFC13294E7AD73CA45012B5C9AADB950CBFEF26609249DFA8972D72C3CA425'
          NEXT_PUBLIC_APP_SALESFORCE_CONSUMER_KEY: '3MVG9HB6vm3GZZR.h84pmASRrblHW95mS8Bpu6bzoqEXHsrYavKNJRMg0px3dl8.aHED6Y9i9ZE5D_EQx20Jk'
          NEXT_PUBLIC_APP_SALESFORCE_SECRET: '6FDFC13294E7AD73CA45012B5C9AADB950CBFEF26609249DFA8972D72C3CA425'
          CRYPTO_SECERT_KEY: 'CghhpgRahZKN0P8SaquPX/k30H+v2QWcKpcH42H9q0w='
          NEXT_PUBLIC_WINDOWS_APP: https://rosdevdi.blob.core.windows.net/reselleros/DealRegAI%20Setup%200.1.0.exe?sp=r&st=2025-01-23T10:48:37Z&se=2050-01-23T18:48:37Z&spr=https&sv=2022-11-02&sr=b&sig=FYDuf4Mx7RSn50wnhBa7kPzvot8%2BQysnoWZ5DqUCv9E%3D
          NEXT_PUBLIC_MAC_APP: https://rosdevdi.blob.core.windows.net/reselleros/DealRegAI-0.1.0.dmg?sp=r&st=2025-01-03T16:31:24Z&se=2050-01-04T00:31:24Z&spr=https&sv=2022-11-02&sr=b&sig=OANEAf941M%2BO3ewV8bOznzxCi9aabjH1OkkBdjasssE%3D


          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: 'close'
